### ISSUE TITLE
Doesn't seem to work well on OSX

### ISSUE THREAD

**Issue by hedefalk** [jancborchardt/hyperminimal#1]
![screen shot 2016-12-16 at 14 51 21](https://cloud.githubusercontent.com/assets/116520/21264921/33e1fce8-c39f-11e6-82f9-227f59dca5a0.png)

OSX 10.12.1

**Comment by jancborchardt** [comment]
@hedefalk thanks for letting me know! :) I kind of already anticipated that it might conflict with the macOS window decorations. (I unfortunately don’t have a macOS to test, am on Ubuntu + Gnome Shell.)

@matheuss sorry if you are not the right person to ask, but is there a way to override the native window title and controls?

**Comment by henrikruscon** [comment]
https://github.com/electron/electron/blob/master/docs/api/frameless-window.md
```
// Hide traffic buttons
exports.decorateBrowserOptions = defaults => Object.assign({}, defaults, {
    titleBarStyle: '',
    transparent: true,
    frame: false
});
```

You'll need additional style changes. You can look at the source of my theme [hyperterm-chesterish](https://github.com/henrikdahl/hyperterm-chesterish). It hides traffic buttons by default on macOS.

Might want to check for platform since it'll require different styles. `process.platform === 'win32'` Windows (both 32/64 bit returns win32) and `process.platform === 'darwin'` macOS.

Would've PR it for you but I'm currently swamped with work. ✌️

**Comment by jancborchardt** [comment]
Oooh thanks a ton for your help @henrikdahl! I don't have macOS to test but will see to work on a pull request to review.

**Comment by jancborchardt** [comment]
See pull request at https://github.com/jancborchardt/hyperminimal/pull/2 – only takes the »hide traffic buttons JS part, so I’m not sure if it works, and sadly can’t test as said.

@henrikdahl if you have some time to look over it that would be greatly appreciated. :) Of course work takes precedence (or holiday time ;)

**Comment by henrikruscon** [comment]
@jancborchardt 

It can't be done without CSS override. JS hides the traffic buttons but Hyper enforces different CSS on macOS to support the traffic buttons.

![skarmavbild 2016-12-20 kl 22 30 20](https://cloud.githubusercontent.com/assets/1430576/21368708/03632070-c704-11e6-96de-4ca0fe84f686.png)

**Comment by henrikruscon** [comment]
I'd help you with the JS part as mentioned in #4 but I currently lack time ✌️
